### ISSUE TITLE
App crashes on segue

### ISSUE THREAD

**Issue by daxrahusen** [rcdilorenzo/Cell-Expander#2]
When trying to do a segue from the Cell Expander, it will crash and tells the following print.

`An instance 0x7a7ccfb0 of class UsabilityApp.TerminologieCell was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7a7d3a30> (
<NSKeyValueObservance 0x7a7d3a90: Observer: 0x7a7ccfb0, Key path: frame, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7a675160>
)`

Seems like it has something to do with registering the observer. Maybe an idea to implement the observer methods in the UITableViewController?

**Comment by loplopLover** [comment]
Same here. I got this error when trying to do back viewcontroller.

**Comment by rcdilorenzo** [comment]
I'll check on this. Thanks for the info!

**Comment by rcdilorenzo** [comment]
@daxrahusen: I'm checking on the issues on this repository. Do you know if this is still an issue? If so, did you end up solving it?
