### ISSUE TITLE
Error with registering the cell

### ISSUE THREAD

**Issue by rishab-yumist** [rcdilorenzo/Cell-Expander#3]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier cell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

```
override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCellWithIdentifier(cellID, forIndexPath: indexPath) as! LegalTableViewCell
    cell.PrivacyPolicyLabel.text = "Test Title"
    return cell
}
```

**Comment by rcdilorenzo** [comment]
You'll need to register the cell in the [storyboard as in this repo](https://github.com/rcdilorenzo/Cell-Expander/blob/master/Cell%20Expander/Base.lproj/Main.storyboard#L17) or in the `viewDidLoad` using the docs specified [here](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UITableView_Class/index.html#//apple_ref/occ/instm/UITableView/registerClass:forCellReuseIdentifier:).

This shouldn't be a problem with the code in this repository.
