### ISSUE TITLE
Swift 2 issue?

### ISSUE THREAD

**Issue by mattiaskronberg** [rcdilorenzo/Cell-Expander#4]
`2015-09-29 12:13:52.283 MyApp[2984:905714] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MyApp.MyCell 0x16002c7b0> for the key path "frame" from <MyApp.MyCell 0x16002c7b0> because it is not registered as an observer.'`

I get this error using Swift 2. This method: 

`override func observeValueForKeyPath(keyPath: String?, ofObject object: AnyObject?, change: [String : AnyObject]?, context: UnsafeMutablePointer<Void>) {
        if keyPath == "frame"
        {
            checkHeight()
        }
    }`

seems slightly changed (`change: [NSObject` is now `change: [String :`, otherwise it won't compile). I'm no iOS expert and can't provide a solution for this, but wanted to let you know. Thanks for an awesome tutorial and repo, despite this.

**Comment by mattiaskronberg** [comment]
`override func tableView(tableView: UITableView, didEndDisplayingCell cell: UITableViewCell, forRowAtIndexPath indexPath: NSIndexPath) {`
`//(cell as! PickerTableViewCell).ignoreFrameChanges()`

`}`

By commenting out the line as shown, it works fine. However, this will of course cause errors, as the observers are never removed.

**Comment by mattiaskronberg** [comment]
Take a look at this code, posted as a comment (not by me) to your YouTube video: 

http://pastebin.com/VaRmuYfU

**Comment by rcdilorenzo** [comment]
You still need to remove the observer but I'll need to see when this is getting called and should not be.

**Comment by mattiaskronberg** [comment]
By using the pastebin code, everything works just fine. It seems like `didEndDisplayingCell` is called when reloading the selected cell.

**Comment by rcdilorenzo** [comment]
Okay, excellent. I'll jump on it when I get the time.

**Comment by odedharth** [comment]
@mattiaskronberg thanks for the fix!

**Comment by odedharth** [comment]
@mattiaskronberg looks like your solution causes this error:
http://stackoverflow.com/questions/16104013/reusable-cell-in-uitableview
