### ISSUE TITLE
How to animate the 2nd view when expand the cell

### ISSUE THREAD

**Issue by heshanlk** [rcdilorenzo/Cell-Expander#5]
I'm not sure how to animate the cell when expand so it can be more user friendly, what is the best way to do that?

**Comment by rcdilorenzo** [comment]
What sort of content do you have in the cell that you need to animate as it opens?

**Comment by heshanlk** [comment]
I have a view, image and labels, as it expand I'm trying to do unfold and fold on collapse animation. I can't figure out how to do that.

**Comment by rcdilorenzo** [comment]
You'll need to modify the function `heightForRowAtIndexPath` in the example to notify the cell to perform the expand animation with constraints. Then, you'll also need to refactor the `checkHeight` cell.

If you need live assistance, feel free to schedule a time at http://hackhands.com/rcdilorenzo/ and I will be glad to help in any way possible.

**Comment by heshanlk** [comment]
Thanks a lot. Sure I'd like to get live assistance too, when the time comes I'll schedule a session with you. Thanks again.
