### ISSUE TITLE
Titles not showing when table loaded

### ISSUE THREAD

**Issue by LonerganOnline** [rcdilorenzo/Cell-Expander#6]
the text only shows when i touch the table row. the title only remains (when in the collapsed state) when i open a section and then open another section without closing the first section. otherwise it works fine but after the screen loads it appears as if there is no content

**Comment by rcdilorenzo** [comment]
Sorry for not getting back to you. Was this just with the sample project or did this occur when you were trying to implement it on your own project?

**Comment by LonerganOnline** [comment]
I am afraid i am no longer working on this project or IOS for that matter and I cant remember the details of the issue.
