### ISSUE TITLE
Last UITableView item issue

### ISSUE THREAD

**Issue by ghost** [rcdilorenzo/Cell-Expander#7]
Hi there, congrats for the great project. But it has a small issue that I think you should take a look:

When you select the last item from the table, after the cell expands, all other that are below the selected one changes their height to 200. It would be nice to fix this to only expand the selected cell. Can you take a look at that?

**Comment by rcdilorenzo** [comment]
Sure @MarcoAurelioVianaAlmeida. As soon as I get a chance, I'll see what I can do.

**Comment by ghost** [comment]
Ok cool!!!

**Comment by rcdilorenzo** [comment]
This might actually be fixed by adding the `estimatedRowHeight` as I discussed in #8 with @Yita55.
