### ISSUE TITLE
expend two cell when running on iOS 8 device

### ISSUE THREAD

**Issue by Yita55** [rcdilorenzo/Cell-Expander#8]
I am trying to run Cell-Expender on multi-device.
When I run it on iOS9, iOS10 device. All function is OK.
But when I run is on iOS8 device, when I click first cell, it will expend two cell.

Would you tell me how to fix it ? Thanks!

BR,
Yita.

**Comment by rcdilorenzo** [comment]
Do you have a test project? I don't think I have the iOS 8 SDK anymore.

**Comment by Yita55** [comment]
I use Xcode simulator that select ios 8 to run.

You can use https://github.com/quantumarun/Demos project.

**Comment by Yita55** [comment]
in this project : https://github.com/quantumarun/Demos

add two line to solve. 


expandTableView.estimatedRowHeight = 40
expandTableView.rowHeight = UITableViewAutomaticDimension

**Comment by rcdilorenzo** [comment]
Feel free to open a pull-request. I see the lines you are referring to in that project. Sorry for the delayed response.
