### ISSUE TITLE
UITableView & UITableViewCell - Swift

### ISSUE THREAD

**Issue by ghost** [rcdilorenzo/Cell-Expander#9]
Hi! I have a project to do which require to use a table, if I click on any cell it should navigates to another view controller but I cannot find the right code to do that, anyone would help? 
PS: this is my first time dealing with tables in Xcode - swift. 
thank you in advance.

**Comment by rcdilorenzo** [comment]
If you're trying to have the cell expand AND go to another controller, you'll need to have a button inside of the expanded cell that pushes the new controller.

If you're trying to just tap on a cell to go to another controller, you'll need to take a look at [tableView(_:didSelectRowAt:)](https://developer.apple.com/reference/uikit/uitableviewdelegate/1614877-tableview) when inside your controller.

Let me know if this doesn't work for you or still need additional clarification.
